[project]
authors = ["Taciclei Souza Hortencio <contact@taciclei.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "poc_api_langraph"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
start = "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

[dependencies]
max = ">=24.6.0,<25"
uvicorn = "*"
python-dotenv = ">=1.0.1,<2"
langgraph = "*"
pydantic = ">=2.4.0"
langchain = "*"
tinydb = ">=4.8.2,<5"
pytest-cov = ">=6.0.0,<7"
fastapi = "==0.100.0"
httpx = ">=0.28.1,<0.29"
pytest-asyncio = ">=0.25.2,<0.26"
openai = ">=1.59.7,<2"
anthropic = ">=0.43.0,<0.44"
google-generativeai = ">=0.8.3,<0.9"
llama-cpp-python = ">=0.2.24,<0.3"
mistralai = ">=0.4.2,<0.5"
requests = ">=2.32.3,<3"
tiktoken = ">=0.8.0,<0.9"
pytest = ">=8.3.4,<9"
grpcio = ">=1.67.1,<2"
psutil = ">=6.1.1,<7"
langchain-community = ">=0.3.14,<0.4"
pydantic-settings = ">=2.7.1,<3"
alembic = ">=1.14.0,<2"
psycopg2-binary = ">=2.9.9,<3"
asyncpg = ">=0.30.0,<0.31"

[pypi-dependencies]
mistralai = ">=0.0.12"
